### ISSUE TITLE
When creating Zend application from scratch

### ISSUE THREAD

**Issue by Petr73ru** [zendframework/zend-stratigility#174]
127.0.0.1:39126 [500]: / - Uncaught Zend\Stratigility\Exception\MissingResponseException: Decorated callable middleware of type Closure failed to produce a response. in /home/peter/Code/Zend/expressive/vendor/zendframework/zend-stratigility/src/Exception/MissingResponseException.php:23
Stack trace:
#0 /home/peter/Code/Zend/expressive/vendor/zendframework/zend-stratigility/src/Middleware/CallableMiddlewareDecorator.php(55): Zend\Stratigility\Exception\MissingResponseException::forCallableMiddleware(Object(Closure))
#1 /home/peter/Code/Zend/expressive/vendor/zendframework/zend-expressive-router/src/Middleware/DispatchMiddleware.php(56): Zend\Stratigility\Middleware\CallableMiddlewareDecorator->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#2 /home/peter/Code/Zend/expressive/vendor/zendframework/zend-stratigility/src/Next.php(127): Zend\Expressive\Router\Middleware\DispatchMiddleware->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#3 /home/peter/Code/Zend/expressive/vendor/zen in /home/peter/Code/Zend/expressive/vendor/zendframework/zend-stratigility/src/Exception/MissingResponseException.php on line 23

**Comment by xtreamwayz** [comment]
That looks like your middleware is not returning a Response. Since you are using the expressive router, I'm guessing it can't find a route for the request and you have not added a NotFoundHandler.
